---

- name: Get clusters
  cm_api:
    endpoint: /clusters
  register: clusters

- name: Set clusters
  set_fact:
    cluster_name: "{{ clusters.json['items'] }}"

# - name: Restart Service
#   include_tasks: restart.yml
#   vars:  
#     cluster: "{{ item.0  }}"
#     service_name: "{{ item.1 }}"
#   with_nested:
#     - "{{ clusters.json['items'] }}"
#     - "{{ service_to_restart }}"


- name: Restart Service
  include_tasks: restart.yml
  vars:  
    cluster: Cluster1
    service_name: "{{ item }}"
  with_items:
    - "{{ service_to_restart }}"