---

- name: Get cluster services
  cm_api:
    endpoint: /clusters/Cluster1/services
  register: services

- set_fact:
    stale_service_count: "{{ services.json | json_query('items[?configStalenessStatus==`STALE`]') | length }}"
    stale_client_config_count: "{{ services.json | json_query('items[?clientConfigStalenessStatus==`STALE`]') | length }}"

- name: Restart {{ service_name }}
  cm_api:
    endpoint: /clusters/Cluster1/services/{{ service_name }}/commands/restart
    method: POST
  register: _command_result
#  when: cluster.name is defined

- name: debug previous command result
  debug:
    msg: "{{ _command_result.json.resultMessage }}"
  when: _command_result.json.success

- name: Re-deploy client configurations
  cm_api:
    endpoint: /clusters/Cluster1/commands/deployClientConfig
    method: POST
    timeout: "{{ client_config_timeout | default(omit) }}"
  when: stale_client_config_count | int > 0

