---
# - name: Perform prerequisite steps
#   block:
#     - name: Maintain krb5.conf file
#       template:
#         src: krb5.conf.j2
#         dest: /etc/krb5.conf
#         owner: root
#         group: root
#         mode: 0644
#         backup: yes
#         force: yes
#       delegate_to: "{{ item }}"
#       with_items: "{{ groups.cluster }}"

- name: Configure Kerberos
  block:
    - name: Check if Kerberized
      cm_api:
        endpoint: /cm/kerberosInfo
        method: GET
      register: _krb_state

    - name: Stop Cloudera Management Services
      cm_api:
        endpoint: /cm/service/commands/stop
        method: POST

    - name: Pick config Template
      set_fact:
        krb_configs_json: "{{ lookup('template', 'kerberos_configs.j2', convert_data=False) }}"

    - name: Apply Kerberos Configs
      cm_api:
        endpoint: /cm/config
        body: "{{ lookup('template', 'kerberos_configs.j2', convert_data=False) }}"
        method: PUT

    - name: Import KDC admin credentials
      cm_api:
        endpoint: /cm/commands/importAdminCredentials?username={{ krb5_kdc_admin_user | urlencode }}&password={{ krb5_kdc_admin_password | urlencode }}
        method: POST
      register: _import_result
      until: _import_result is not failed
      retries: 3
      delay: 10
      
    - name: debug previous command result
      debug:
        msg: "{{ _import_result.json.resultMessage }}"
      when: _import_result.json.success

    - name: Get configs template
      set_fact:
        krb_enabled_json: "{{ lookup('template', 'configure_for_kerberos.j2', convert_data=False) }}"


    - name: Start Cloudera Management Services
      include_role:
        name: operations/restart_cms

