---
keytrustee_server_conf_dir: /var/lib/keytrustee/.keytrustee
keytrustee_server_org_name: cloudera
keytrustee_server_org_email: admin@example.com
keytrustee_server_key_files:
  - gpg.conf
  - keytrustee.conf
  - logging.conf
  - pubring.gpg
  - pubring.gpg~
  - random_seed
  - secring.gpg
  - trustdb.gpg
