#!/usr/bin/expect
spawn /home/training/training_materials/admin/scripts/dropDBsAndUsers.sh
sleep 2
expect "*>" { send "DROP DATABASE IF EXISTS cmserver;\r"}
expect "*>" { send "DROP USER cmserveruser;\r"}
expect "*>" { send "DROP DATABASE IF EXISTS rman;\r"}
expect "*>" { send "DROP USER rmanuser;\r"}
expect "*>" { send "DROP DATABASE IF EXISTS amon;\r"}
expect "*>" { send "DROP USER amonuser;\r"}
expect "*>" { send "DROP DATABASE IF EXISTS metastore;\r"}
expect "*>" { send "DROP USER hiveuser;\r"}
expect "*>" { send "DROP DATABASE IF EXISTS oozie;\r"}
expect "*>" { send "DROP USER oozieuser;\r"}
expect "*>" { send "DROP DATABASE IF EXISTS hue;\r"}
expect "*>" { send "DROP USER hueuser;\r"}
expect "*>" { send "DROP DATABASE IF EXISTS director;\r"}
expect "*>" { send "DROP USER director;\r"}
expect "*>" { send "DROP DATABASE IF EXISTS hive;\r"}
expect "*>" { send "DROP USER hiveuser;\r"}
expect "*>" { send "DROP USER 'director'@'localhost';\r"}
expect "*>" { send "DROP USER 'cmserveruser'@'localhost';\r"}
expect "*>" { send "DROP USER 'rmanuser'@'localhost';\r"}
expect "*>" { send "DROP USER 'training'@'gateway';\r"}
expect "*>" { send "DROP USER 'training'@'gateway.example.com';\r"}
expect "*>" { send "DROP USER 'training'@'worker-1.example.com';\r"}
expect "*>" { send "DROP USER 'training'@'worker-2.example.com';\r"}
expect "*>" { send "DROP USER 'training'@'worker-3.example.com';\r"}
expect "*>" { send "DROP USER 'training'@'worker-1';\r"}
expect "*>" { send "DROP USER 'training'@'worker-2';\r"}
expect "*>" { send "DROP USER 'training'@'worker-3';\r"}


expect "*>" { send "exit;\r"}
sleep 4
