# Copyright 2022 Cloudera, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- hosts: database
  gather_facts: False
  tasks:
    - name: Drop scm Database
      become: yes
      vars:
        ansible_ssh_pipelining: true
      mysql_db:
        name: scm
        state: absent

    - name: Drop amon Database
      become: yes
      vars:
      mysql_db:
        name: amon
        state: absent

    - name: Drop rman Database
      become: yes
      vars:
      mysql_db:
        name: rman
        state: absent

    - name: Restore scm Database
      become: yes
      mysql_db:
        name: scm
        state: import
        target: /var/scm_621.sql

    - name: Restore amon Database
      become: yes
      vars:
      mysql_db:
       name: amon
       state: import
       target: /var/amon_621.sql

    - name: Restore rman Database
      become: yes
      vars:
      mysql_db:
        name: rman
        state: import
        target: /var/rman_621.sql

- hosts: all
  tasks:
   - name: Remove Agent Runtime State
     shell: "rm -rf /var/run/cloudera-scm-agent /var/lib/cloudera-scm-agent/response.avro"

- hosts: ServiceMonitor
  gather_facts: False
  tasks:
   - name: Execute Service Monitor Directory Restore
     unarchive:
       src:  /var/lib/cloudera-service-monitor_6.2.1.tgz
       dest: /var/lib

- hosts: HostMonitor
  gather_facts: False
  tasks:
   - name: Execute Host Monitor Directory Restore
     unarchive:
       src:  /var/lib/cloudera-host-monitor_6.2.1.tgz
       dest: /var/lib    

- hosts: EventServer
  gather_facts: False
  tasks:
   - name: Execute Service Monitor Directory Restore
     unarchive:
       src:  /var/lib/cloudera-scm-eventserver_6.2.1.tgz
       dest: /var/lib

- hosts: NavigatorMetadataServer
  gather_facts: False
  tasks:
   - name: Execute navms Directory Restore
     unarchive:
       src:  /var/lib/cloudera-scm-navigator_6.2.1.tgz
       dest: /var/lib
