---
- name: Remove current Cloudera Manager yum repo
  yum_repository:
    name: cloudera-manager
    state: absent
  notify: yum-clean-metadata

- name: yum-clean-metadata if required
  meta: flush_handlers

- name: Add Cloudera Manager yum repository
  yum_repository:
    name: cloudera-manager
    description: Cloudera Manager
    baseurl: file:///home/training/software/cm7.6.1
#    baseurl: "{{ cloudera_manager_repo_url }}"
    gpgkey: "{{ cloudera_manager_repo_key }}"
    gpgcheck: no
    enabled: yes
    state: present
