---
- name: Deploy krb5.conf
  hosts: cluster
  become: yes
  gather_facts: no
  roles:
    - role: configuration/kerberos
      when: security | default(false)


- name: Deploy Cloudera Management Service and CM template
  hosts: cmhost
  connection: local
  become: yes
  gather_facts: yes
  roles:
    - role: deployment/services/mgmt

    - role: configuration/autotls
      when: security | default(false)

    - role: configuration/kerberos-tls
      when: security | default(false)

    - role: deployment/cluster

