---
- name: Apply Lab Advancing steps
  hosts: ipaserver
  become: yes
  tasks:
    - name: Restore IPA server to the initial state
      block:
        - name: Pick the latest IPA backup file
          shell: /usr/bin/ls -Art /var/lib/ipa/backup/ | tail -n 1  
          register: _command_result

        - name: Parse CM clusters summary 
          set_fact:
            ipa_backup_file: "{{ _command_result.stdout }}"

        - name: Restore IPA server from a backup file
          shell: echo yes | sudo ipa-restore /var/lib/ipa/backup/{{ _command_result.stdout }} -p password1
          register: _restore_result
#          failed_when: "'The ipa-backup command was successful' not in _restore_result.stderr_lines"

        - name: Display IPA restore command result
          debug: 
            msg: "{{ _restore_result.stderr_lines | last }}"


        - name: Change global_policy peroperties
          shell: | 
            echo password1 | kinit admin
            ipa pwpolicy-show global_policy
            ipa pwpolicy-mod --maxlife=60 --minlife=1 --minclasses=3 --minlength=8

        - name: Create the sudo rule for admins_sudo
          shell: | 
            echo password1 | kinit admin
            ipa sudorule-add admins_sudo --hostcat=all --runasusercat=all --runasgroupcat=all --cmdcat=all
            ipa sudorule-add-option admins_sudo --sudooption='!authenticate'
            ipa sudorule-add-user admins_sudo --group admins
            ipa sudorule-find All

        - name: Manage IT Specialist role privileges and supergroup membership
          shell: | 
            echo password1 | kinit admin
            ipa role-add-privilege --privileges="Group Administrators" "IT Specialist"
            ipa role-add-member --users="sam_sec" "IT Specialist"
            ipa group-add-member --users="allan_admin" supergroup

- name: Manage SSSD service
  hosts: cluster
  become: yes
  tasks:
    - name: Set sssd to enumerate users and groups
      lineinfile:
        path: /etc/sssd/sssd.conf
        insertafter: "^\\[domain/.+\\]"
        regexp: "^enumerate"
        line: "enumerate = True"
      notify:
        - restart sssd
      when: "security | default(false) and sdx == 'yes' | default('no')"
  handlers:
    - name: restart sssd
      service:
        name: sssd
        state: restarted