---
- name: Setup Key Trustee Server HA
  import_playbook: setup_kts_ha.yml
  tags:
    - kts

- name: Create Key Trustee Server organisation
  hosts: kts-1
  become: yes
  tasks:
    - shell: >
        keytrustee-orgtool add
        -n {{ keytrustee_server_org_name }}
        -c {{ keytrustee_server_org_email }}
        --confdir {{ keytrustee_server_conf_dir }}
  tags:
    - kts

- name: Update Key Secret 
  hosts: kts-1
  become: yes
  tasks:
    - shell: >
        keytrustee-orgtool set-auth
        --name {{ keytrustee_server_org_name }}
        --secret "oXf6wmcoy3U/Zk4yAykcUw=="
  tags:
    - kts

- name: Enable KMS HA
  import_playbook: setup_kms_ha.yml
  tags:
    - kms

- name: Restart Cluster Service
  hosts: cloudera_manager
  roles:
    - operations/restart_service
  tags:
    - kts
  vars:
    cluster_restart_timeout: 3600
    service_to_restart: 
      - ranger_kms_kts
      - hive_on_tez
