---

- name: Create temp directory for keys
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - file:
        path: "{{ local_temp_dir }}/kms"
        owner: root
        group: root
        state: directory
        mode: 0777

- name: Fetch keys from first KMS server
  hosts: kms-1
  become: yes
  gather_facts: no
  tasks:
    - fetch:
        src: "{{ kms_conf_dir }}/{{ item }}"
        dest: "{{ local_temp_dir }}/kms"
        fail_on_missing: no
      with_items: "{{ kms_key_files }}"

- name: Copy keys to other KMS servers
  hosts: kms-2
  become: yes
  gather_facts: no
  tasks:
    - copy:
        src: "{{ local_temp_dir }}/kms/kms-1{{ kms_conf_dir }}/"
        dest: "{{ kms_conf_dir }}"
        owner: "{{ kms_user }}"
        group: "{{ kms_group }}"
        mode: 0600

- name: Delete temp directory
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - file:
        path: "{{ local_temp_dir }}/kms"
        state: absent


