---
#- name: Recursively change ownership of a directory
#  ansible.builtin.file:
#    path: /var/lib/keytrustee
#    state: directory
#    recurse: yes
#    owner: keytrustee
#    group: keytrustee
#  delegate_to: kts-1
- name: Run ktadmin init on kts-1
  shell: |
    ktadmin init 
  delegate_to: kts-1

#- name: Recursively change ownership of a directory
#  ansible.builtin.file:
#    path: /var/lib/keytrustee
#    state: directory
#    recurse: yes
#    owner: keytrustee
#    group: keytrustee
#  delegate_to: kts-2


- name: Run the rsync command to copy the .trustee directory to kts-2
  shell: |
    rsync -zav --rsh=ssh --exclude .ssl /var/lib/keytrustee/.keytrustee kts-2.example.com:/var/lib/keytrustee/
  delegate_to: kts-1

- name: Run ktadmin init on kts-2
  shell: |
    ktadmin init
  delegate_to: kts-2

# verify the KTS fingerprint
#- name: 
#  shell: | 
#    curl -k https://kts-1.example.com:11371/?a=fingerprint
#  register: kts1_fingerprint
#
#- name:
#  shell: |
#    curl -k https://kts-2.example.com:11371/?a=fingerprint
#  register: kts2_fingerprint
#
#- name: 
#  debug:
#    msg: All Good
#  when: kts1_fingerprint.stdout == kts2_fingerprint


