---

- set_fact:
    cluster: "Key Trustee Server Cluster"

#- fail:
#    msg: No Key Trustee Server cluster was found
#  when: cluster.name is not defined

- name: Restart Key Trustee Server service
  cm_api:
    endpoint: /clusters/{{ cluster | urlencode() }}/services/keytrustee_server/commands/restart
    method: POST
#  when: cluster.name is defined

- name: Setup Key Trustee Server database replication
  cm_api:
    endpoint: /clusters/{{ cluster | urlencode() }}/services/keytrustee_server/commands/SetupSyncReplicationCommand
    method: POST
#  when: cluster.name is defined

- name: Restart Key Trustee Server service
  cm_api:
    endpoint: /clusters/{{ cluster | urlencode() }}/services/keytrustee_server/commands/restart
    method: POST
#  when: cluster.name is defined
