---
- name: Generate CMS deployment JSON file
  template:
    src: addCMS.j2
    dest: /home/training/config/addCMS.json
    force: yes
    backup: yes

- name: Add and Configure Cloudera Management Services
  script: add-mgmt-service.sh

- name: Restart Cloudera Management Service
  cm_api:
    endpoint: /cm/service/commands/restart
    method: POST

- name: Pause to allow CMS to startup
  pause:
    seconds: 30

- debug:
    var: start_resp.json.id
    verbosity: 1

