---
- name: Configure Kerberos
  block:
    - name: Maintain krb5.conf file
      template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
        force: yes


#     - name: Stop Cluster Services
#       uri:
#         url: "https://cmhost:7183/api/v44/clusters/Cluster1/commands/stop"
#         method: POST
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: _stop_resp
# #      until: not _stop_resp.json.active
# #      retries: 20
# #      delay: 30
#       failed_when: "'startTime' not in _stop_resp.content"

#     - name: Previous command result
#       uri:
#         url: "https://cmhost:7183/api/v44/commands/{{ _stop_resp.json.id }}"
#         method: GET
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _command3_result
#       until: not _command3_result.json.active
#       retries: 30
#       delay: 30

#     - name: debug previous command result
#       debug:
#         msg: "{{ _command3_result.json.resultMessage }}"
#       when: _command3_result.json.success

#     - name: Stop Cloudera Management Services
#       uri:
#         url: "https://cmhost:7183/api/v44/cm/service/commands/stop"
#         method: POST
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: start_resp
#       until: not start_resp.json.active
#       retries: 10
#       delay: 20
#       failed_when: "'startTime' not in start_resp.content"

#     - name: Pick config Template
#       set_fact:
#         krb_configs_json: "{{ lookup('template', 'kerberos_configs.j2', convert_data=False) }}"

#     - name: Apply Kerberos Configs
#       uri:
#         url: "https://cmhost:7183/api/v44/cm/config"
#         method: PUT
#         body_format: json
#         #src: kerberos_configs.j2
#         body: "{{ krb_configs_json | to_json }}"
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: start_resp
#       #failed_when: "'startTime' not in start_resp.content"


#     - name: Import Admin Credencials
#       uri:
#         url: "https://cmhost:7183/api/v43/cm/commands/importAdminCredentials?password=password1&username=admin%40EXAMPLE.COM"
#         method: POST
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: _import_result
#       until: _import_result is not failed
#       retries: 3
#       delay: 10
#       failed_when: "'startTime' not in _import_result.content"


#     - name: Import Admin Credencials
#       uri:
#         url: "https://cmhost:7183/api/v43/commands/{{ _import_result.json.id }}"
#         method: GET
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: _import_result2
#       until: not _import_result2.json.active
#       retries: 5
#       delay: 20
      


#     - name: debug previous command result
#       debug:
#         msg: "{{ _import_result2.json.resultMessage }}"
#       when: _import_result2.json.success

#     - name: Get configs template
#       set_fact:
#         krb_enabled_json: "{{ lookup('template', 'configure_for_kerberos.j2', convert_data=False) }}"

#     - name: Apply Kerberos Configs
#       uri:
#         url: "https://cmhost:7183/api/v43/clusters/Cluster1/commands/configureForKerberos"
#         method: POST
#         body_format: json
#         body: "{{ krb_enabled_json | to_json }}"
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: enable_krb_result
#       until: not enable_krb_result.json.active
#       retries: 20
#       delay: 30
    
#     - name: Previous command result
#       uri:
#         url: "https://cmhost:7183/api/v44/commands/{{ enable_krb_result.json.id }}"
#         method: GET
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _command4_result
#       until: not _command4_result.json.active
#       retries: 30
#       delay: 20

#     - name: debug previous command result
#       debug:
#         msg: "{{ _command4_result.json.resultMessage }}"
#       when: _command4_result.json.success

#     - name: Generate Missing Credentials Command Result
#       uri:
#         url: "https://cmhost:7183/api/v44/commands/{{ enable_krb_result.json.id+1 }}"
#         method: GET
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _command5_result
#       until: "not _command5_result.json.active"
#       retries: 30
#       delay: 20

#     - name: debug previous command result
#       debug:
#         msg: "{{ _command5_result.json.resultMessage }}"
#       when: _command5_result.json.success



 
#     - name: Deploy Cluster Client Config
#       uri:
#         url: "https://cmhost:7183/api/v43/clusters/Cluster1/commands/deployClusterClientConfig"
#         method: POST
#         body_format: json
#         body: "{{ lookup('template', 'client_config.j2', convert_data=False) }}"
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: _deploy_krb_result
# #      until: not _deploy_krb_result.json.active
# #      retries: 20
# #      delay: 30
#     - name: Track the command progress
#       uri:
#         url: "https://cmhost:7183/api/v44/commands/{{ _deploy_krb_result.json.id }}"
#         method: GET
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _command2_result
#       until: not _command2_result.json.active
#       retries: 30
#       delay: 5

#     - name: debug previous command result
#       debug:
#         msg: "{{ _command2_result.json.resultMessage }}"
#       when: _command2_result.json.success

#     - name: Deploy Client Configs
#       uri:
#         url: "https://localhost:7183/api/v44/clusters/Cluster1/commands/deployClientConfig"
#         method: POST
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _deploy_result

#     - name: debug deploy configs command
#       debug:
#         msg: "{{ _deploy_result.json.id }}"

#     - name: Previous command result
#       uri:
#         url: "https://cmhost:7183/api/v44/commands/{{ _deploy_result.json.id }}"
#         method: GET
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _command_result
#       until: not _command_result.json.active
#       retries: 20
#       delay: 2

#     - name: debug previous command result
#       debug:
#         msg: "{{ _command_result.json.resultMessage }}"
#       when: _command_result.json.success


#     - name: Restart Cloudera Management Services
#       uri:
#         url: "https://cmhost:7183/api/v10/cm/service/commands/start"
#         method: POST
#         status_code: 200
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         validate_certs: no
#       register: start_resp
#       until: not start_resp.json.active
#       retries: 10
#       delay: 20
#       failed_when: "'startTime' not in start_resp.content"

#     - name: Pause to allow CMS to startup
#       pause:
#         seconds: 30


#     - name: Restart Cluster services
#       uri:
#         url: "https://localhost:7183/api/v10/clusters/Cluster1/commands/restart"
#         method: POST
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _restart_result

#     - name: Previous command result
#       uri:
#         url: "https://cmhost:7183/api/v44/commands/{{ _restart_result.json.id }}"
#         method: GET
#         body_format: json
#         force_basic_auth: yes
#         user: admin
#         password: admin
#         return_content: yes
#         status_code: 200
#         validate_certs: no
#       register: _command2_result
#       until: not _command2_result.json.active
#       retries: 30
#       delay: 60

#     - name: debug previous command result
#       debug:
#         msg: "{{ _command2_result.json.resultMessage }}"
#       when: _command2_result.json.success
