---

- name: Check for a local cluster definition file
  stat:
    path: "{{ cluster_definition }}/cluster.yml"
  register: cluster_def

- name: Load the local cluster definition file
  include_vars:
    file: "{{ cluster_definition }}/cluster.yml"
    name: _definition
  when: cluster_def.stat.exists